[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.railway]
processes = ["web"]

[services.mysql]
image = "mysql:8" 