[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.railway]
processes = ["web"]

# Add PHP configuration
[nixpacks]
php_version = "8.1"
web_command = "php -S 0.0.0.0:$PORT -t backend"

# MySQL Service configuration
[services.mysql]
image = "mysql:8"
environment = [
  "MYSQL_DATABASE=sim_db",
  "MYSQL_USER=railway",
  "MYSQL_PASSWORD=${MYSQL_PASSWORD}",
  "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
] 